name: shop
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_swiper_view: ^1.1.8
  event_bus: ^2.0.0
  shared_preferences: ^2.0.13
  sqflite: ^2.3.2
  flutter_screenutil: ^5.9.0-beta
  provider: ^6.1.2
  path: ^1.9.0
  delightful_toast: ^1.1.0
  dio: ^4.0.0
  intl: ^0.17.0
  crypto: ^3.0.0
  flutter_slidable: ^3.1.0
  swipe_deck: ^1.1.0
  smooth_page_indicator: ^1.1.0
  uuid: ^3.0.4
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:  
    - assets/images/

